name: shop_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  shared_preferences: ^2.0.15
  http: ^1.2.1
  google_sign_in: ^5.2.4
  local_auth: ^2.1.3
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  ionicons: ^0.2.2
  google_fonts: ^6.2.1
  iconsax: ^0.0.8
  mysql1: 0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - google_fonts/
